version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/New_York
    open-pull-requests-limit: 10

    # Group rules
    groups:
      react-stack:
        applies-to: version-updates
        patterns:
          - "react"
          - "react-dom"
          - "@types/react*"
        update-types: ["minor","patch"]   # majors stay separate

      vite-tooling:
        applies-to: version-updates
        patterns:
          - "vite"
          - "@vitejs/*"
          - "vite-plugin-*"
        update-types: ["minor","patch"]

      lint-and-format:
        applies-to: version-updates
        dependency-type: development
        patterns:
          - "eslint*"
          - "@typescript-eslint/*"
          - "prettier*"
          - "@testing-library/*"
        update-types: ["minor","patch"]

      # group *security* updates into single PRs
      security-all:
        applies-to: security-updates
        patterns: ["*"]                   # all npm advisories
        # optional: limit scope
        # update-types: ["patch","minor"]

    # keep majors individual for risky deps
    ignore:
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "vite"
        update-types: ["version-update:semver-major"]
